name: Build Release

on:
  workflow_dispatch:
    inputs:
      versionName:
        required: true
        description: This releases version name
        default: "1.0.0"
      versionCode:
        required: true
        description: This releases version code
        default: "1"
      description:
        required: false
        description: Description of this release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      - name: Set version
        uses: chkfung/android-version-actions@v1.1
        with:
          gradlePath: app/build.gradle.kts
          versionCode: ${{github.event.inputs.versionCode}}
          versionName: ${{github.event.inputs.versionName}}

      - name: Build signed APK
        run: |
          echo "${{ secrets.keystore }}" | base64 -d > $GITHUB_WORKSPACE/signing-key.jks
          chmod +x ./gradlew
          ./gradlew assembleRelease -Pandroid.injected.signing.store.file=$GITHUB_WORKSPACE/signing-key.jks -Pandroid.injected.signing.store.password=${{ secrets.keystore_password }} -Pandroid.injected.signing.key.alias=${{ secrets.key_alias }} -Pandroid.injected.signing.key.password=${{ secrets.key_password }}

      - name: Release
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          tag="${{ github.event.inputs.versionCode }}"
          git tag "$tag"
          git push origin "$tag"
          gh release create "$tag" \
            --title "${{ github.event.inputs.versionName }}" \
            --notes "${{ github.event.inputs.description }}" \
            app/build/outputs/apk/release/app-release.apk
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
